# Generated by Django 5.1.1 on 2024-10-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
